CREATE TABLE COMPUTADORA(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    PROCESADOR NVARCHAR2(100),
    RAM NUMBER,
    CAPACIDAD NVARCHAR2(10),
    COLOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPUTADORA_PK PRIMARY KEY(ID_COMPU)
);


CREATE SEQUENCE SEQ_COMPU
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- TRIGGER BEFORE --> ANTES
-- PARA CREAR EL ID_COMPU DE FORMA AUTOMATICA CON LA SECUENCIA
CREATE OR REPLACE TRIGGER TR_COMPU_ID
BEFORE INSERT ON COMPUTADORA -- ANTES DE QUE OCURRA EN LA TABLA COMPUTADORA
FOR EACH ROW
BEGIN
-- SI NO SE PROPORCIONA UN ID, LO ASIGNA CON LA SECUENCIA
    IF :NEW.ID_COMPU IS NULL THEN
        :NEW.ID_COMPU := SEQ_COMPU.NEXTVAL;
    END IF;
END;
/ -- INDICADOR

DROP TABLE COMPUTADORA;

INSERT INTO COMPUTADORA(MARCA, MODELO, PROCESADOR, RAM, CAPACIDAD, COLOR, PRECIO)
VALUES('HP', 'INSPIRON', 'i7', 16, '500GB', 'ROJO', 600);
INSERT INTO COMPUTADORA(MARCA, MODELO, PROCESADOR, RAM, CAPACIDAD, COLOR, PRECIO)
VALUES('DELL', 'MONSTER', 'i8', 16, '500GB', 'ROJO', 600);

SELECT * FROM COMPUTADORA;
COMMIT;