-- TABLA RESPALDO
CREATE TABLE MEDICAMENTO_PRD(
    ID_MEDICAMENTO NUMBER,
    NOMBRE_GENERICO NVARCHAR2(100),
    NOMBRE_COMERCIAL NVARCHAR2(100),
    DESCRIPCION NVARCHAR2(255),
    LABORATORIO NVARCHAR2(100),
    PRECIO NUMBER,
    TIPO_SUMISTRO NVARCHAR2(100),
    CONSTRAINT MED_PRD_PK PRIMARY KEY(ID_MEDICAMENTO)
);

INSERT INTO MEDICAMENTO VALUES(1, 'TEMPRA', 'PARACETAMOL 500MG', 'ANALGESICO Y ANTIPIRETICO DE USO COMUN', 'LABORATORIOS GENERICOS', 250, 'TABLETAS');
INSERT INTO MEDICAMENTO VALUES(2, 'ADVIL', 'IBUPROFENO 400MG', 'ANTINFLAMATORIO PARA GOLPES', 'FARMACEUTICA DELTA', 320, 'CAPSULAS');
INSERT INTO MEDICAMENTO VALUES(3, 'AMOXIL', 'AMOXICILINA 500MG', 'ANTIBIOTICO PARA TRATAR INFECCIONES', 'BIOLAB', 375, 'CAPSULAS');
INSERT INTO MEDICAMENTO VALUES(4, 'CLARITIN', 'LORATADINA 10MG', 'ANTIHISTAMINICO QUE TRATA DIFERENTES ALERGIAS', 'SALUDPHARMA', 195, 'TABLETAS');
INSERT INTO MEDICAMENTO VALUES(5, 'LOSEC', 'OMEPRAZOL 2ML', 'INHIBIDOR PARA CONTRARESTAR LA GASTRITIS', 'GASTROMED', 110, 'INYECCION');
INSERT INTO MEDICAMENTO VALUES(6, 'DOLGENIL', 'PARACETAMOL 650MG', 'ANALGESICO PARA DOLORES MODERADOS', 'LABORATORIOS GENERICOS', 270, 'TABLETAS');
INSERT INTO MEDICAMENTO VALUES(7, 'FLEXIMED', 'IBUPROFENO 600MG', 'ANTINFLAMATORIO Y ANALGESICO MUSCULAR', 'FARMACEUTICA DELTA', 340, 'CAPSULAS');
INSERT INTO MEDICAMENTO VALUES(8, 'AMOXIDAL', 'AMOXICILINA + ÁCIDO CLAVULÁNICO', 'ANTIBIOTICO DE AMPLIO ESPECTRO', 'BIOLAB', 450, 'SUSPENSION');
INSERT INTO MEDICAMENTO VALUES(9, 'LORATIN', 'LORATADINA 5MG/5ML', 'TRATAMIENTO DE ALERGIAS EN NIÑOS', 'BIOLAB', 210, 'JARABE');
INSERT INTO MEDICAMENTO VALUES(10, 'OMEPRIX', 'OMEPRAZOL 20MG', 'TRATAMIENTO DE REFLUJO GÁSTRICO', 'GASTROMED', 130, 'CAPSULAS');
INSERT INTO MEDICAMENTO VALUES(11, 'TERMOGESIC', 'PARACETAMOL + CAFEINA', 'ANALGESICO Y ESTIMULANTE SUAVE', 'LABORATORIOS GENERICOS', 290, 'TABLETAS');
INSERT INTO MEDICAMENTO VALUES(12, 'IBUDOL', 'IBUPROFENO 200MG', 'ALIVIO DE DOLORES LEVES', 'BIOLAB', 310, 'TABLETAS');
INSERT INTO MEDICAMENTO VALUES(13, 'BIOCILINA', 'AMOXICILINA 250MG', 'USO PEDIATRICO CONTRA INFECCIONES BACTERIANAS', 'BIOLAB', 360, 'SUSPENSION');
INSERT INTO MEDICAMENTO VALUES(14, 'CLARIDIN', 'LORATADINA + PSEUDOEFEDRINA', 'ANTIALERGICO CON EFECTO DESCONGESTIVO', 'SALUDPHARMA', 230, 'TABLETAS');
INSERT INTO MEDICAMENTO VALUES(15, 'GASTRUM', 'OMEPRAZOL 40MG', 'TRATAMIENTO INTENSIVO DE ULCERAS', 'GASTROMED', 150, 'CAPSULAS');
COMMIT;

DELETE FROM MEDICAMENTO;

-- PROCEDURE PARA HACER EL RESPALDO
CREATE OR REPLACE PROCEDURE PR_RESPALDO_MEDICAMENTO(
    _DESCUENTO IN NUMBER
)
IS
BEGIN
    DELETE FROM MEDICAMENTO_PRD;
    INSERT INTO MEDICAMENTO_PRD(ID_MEDICAMENTO, NOMBRE_GENERICO, NOMBRE_COMERCIAL, DESCRIPCION, LABORATORIO, PRECIO, TIPO_SUMISTRO)
    SELECT ID_MEDICAMENTO, NOMBRE_GENERICO, NOMBRE_COMERCIAL, DESCRIPCION, LABORATORIO, PRECIO, TIPO_SUMISTRO FROM MEDICAMENTO;
END;
/

-- COMPROBACIÓN
EXECUTE PR_RESPALDO_MEDICAMENTO;

DELETE FROM MEDICAMENTO_PRD;
SELECT * FROM MEDICAMENTO;
SELECT * FROM MEDICAMENTO_PRD;



/* CREAR LOS SIGUIENTES PROCEDURES
    1.- APLICAR UN DESCUENTO DEL 10% A TODOS LOS MEDICAMENTOS
    2.- ELIMINAR UN MEDICAMENTO POR ID
    3.- CREAR UN PR QUE RECIBA COMO PARAMETRO EL NOMBRE DEL LABORATORIO Y RETORNE
    TODOS LOS MEDICAMENTOS ASOCIADOS A ESE LABORATORIO
*/


-- APLICAR DESCUENTO
CREATE OR REPLACE PROCEDURE PR_APLICAR_DESCUENTO_MED(
    M_DESCUENTO IN NUMBER
)
IS
BEGIN
    UPDATE MEDICAMENTO
    SET PRECIO = PRECIO - (PRECIO * (M_DESCUENTO / 100));
    
    DBMS_OUTPUT.PUT_LINE('DESCUENTO DEL ' || M_DESCUENTO || '% APLICADO CORRECTAMENTE A TODOS LOS MEDICAMENTOS');
    
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL APLICAR EL DESCUENTO: ' || SQLERRM);
END;
/ -- INDICADOR

-- ELIMINAR MEDICAMENTO POR ID
CREATE OR REPLACE PROCEDURE PR_ELIMINAR_MED_POR_ID(
    M_ID_MED IN NUMBER
)
IS
    NOM_MED NVARCHAR2(100);
BEGIN
    SELECT NOMBRE_GENERICO INTO NOM_MED FROM MEDICAMENTO WHERE ID_MEDICAMENTO = M_ID_MED;
    DELETE FROM MEDICAMENTO WHERE ID_MEDICAMENTO = M_ID_MED;
    DBMS_OUTPUT.PUT_LINE('EL MEDICAMENTO "' || NOM_MED || '" FUE ELIMINADO CORRECTAMENTE');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EL MEDICAMENTO: ' || SQLERRM);
END;
/ -- INDICADOR

-- MEDICAMENTOS ASOCIADOS A UN LABORATORIO
CREATE OR REPLACE PROCEDURE PR_MOSTRAR_MED_POR_LABORATORIO(
    M_LABORATORIO IN NVARCHAR2
)
IS
    TOTAL_MED NUMBER := 0;
    LAB_FORMAT NVARCHAR2(100);
BEGIN
    LAB_FORMAT := LOWER(M_LABORATORIO);
    
    SELECT COUNT(*) INTO TOTAL_MED
    FROM MEDICAMENTO
    WHERE LOWER(LABORATORIO) = LAB_FORMAT;
    IF TOTAL_MED = 0 THEN
        DBMS_OUTPUT.PUT_LINE('NO HAY MEDICAMENTOS PARA EL LABORATORIO "' || LAB_FORMAT || '"');
    ELSE
        FOR R IN (
            SELECT * FROM MEDICAMENTO
            WHERE LOWER(LABORATORIO) = LAB_FORMAT
        ) LOOP
            DBMS_OUTPUT.PUT_LINE('ID: ' || R.ID_MEDICAMENTO ||
                                 ', NOMBRE GENERICO: ' || R.NOMBRE_GENERICO ||
                                 ', NOMBRE COMERCIAL: ' || R.NOMBRE_COMERCIAL ||
                                 ', PRECIO: ' || R.PRECIO ||
                                 ', LABORATORIO: ' || R.LABORATORIO);
        END LOOP;
    END IF;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL BUSCAR LOS MEDICAMENTOS: ' || SQLERRM);
END;
/ -- INDICADOR

EXECUTE PR_APLICAR_DESCUENTO_MED(10);
EXECUTE PR_ELIMINAR_MED_POR_ID(15);
EXECUTE PR_MOSTRAR_MED_POR_LABORATORIO('BOLAB');

SELECT * FROM MEDICAMENTO;