CREATE TABLE PELICULA(
    ID_PELICULA NUMBER,
    TITULO NVARCHAR2(100),
    DIRECTOR NVARCHAR2(100),
    GENERO NVARCHAR2(100),
    ANIO_ESTRENO NUMBER,
    DURACION_MIN NUMBER,
    RECAUDACION NUMBER,
    CONSTRAINT PELICULA_PK PRIMARY KEY(ID_PELICULA)
);

INSERT INTO PELICULA VALUES(1, 'TITANIC', 'JAMES CAMERON', 'ROMANCE', 1997, 195, 2200000000);
INSERT INTO PELICULA VALUES(2, 'AVATAR', 'JAMES CAMERON', 'CIENCIA FICCCION', 2009, 162,  280000000);
INSERT INTO PELICULA VALUES(3, 'The Matrix', 'Lana Wachowski, Lilly Wachowski', 'Ciencia Ficción', 1999, 136, 466000000);
INSERT INTO PELICULA VALUES(4, 'Inception', 'Christopher Nolan', 'Ciencia Ficción', 2010, 148, 829000000);
INSERT INTO PELICULA VALUES(5,'AVENGERS: ENDGAME','ANTHONY Y JOE RUSSO','SUPERHÉROES',2019,181,2797800564);
INSERT INTO PELICULA VALUES(6,'INTERSTELLAR','CHRISTOPHER NOLAN','CIENCIA FICCIÓN',2014,169,701729206);
INSERT INTO PELICULA VALUES(7,'Madagascar','Eric Darnell','COMEDIA',2005,85,532680671);
INSERT INTO PELICULA VALUES(8,'CARS','John Lasseter','COMEDIA',2006,117, 461983149);
INSERT INTO PELICULA VALUES(9,'TOYSTORY','PIXAR','DIBUJOS ANIMADOS',1995,162,30000000);

/*
    1.- MOSTRAR LAS PELÍCULAS ORDENADAS POR RECAUDACIÓN DE MAYOR A MENOR, APLICANDO UN FORMATO A LA MONEDA (EJEMPLO: $220,000,000)
    2.- CALCULAR EL PROMEDIO DE RECAUDACIÓN DE LAS PELICULAS ESTRENADAS DESPUES DEL 2002
    3.- MOSTRAR LAS PELÍCULAS QUE DUREN MÁS DE 150 MINUTOS Y CONVERTIR EL TÍTULO A MINÚSCULAS
    4.- CONSULTAR LOS REGISTROS CUYO GÉNERO SEA CIENCIA FICCIÓN Y ORDENAR POR ANIO DE ESTRENO DEL MÁS ANTIGUO AL MÁS RECIENTE
    5.- MOSTRAR LAS PELICULAS CUYA RECAUDACION ESTE ENTRE 500,000,000 Y 1,500,000,000
    6.- MOSTRAR LAS PELICULAS DE GÉNERO DE COMEDIA Y AGREGAR AL FINAL DE LA RECAUDACIÓN LA PALABRA PESOS
    7.- CONTAR CUANTAS PELICULAS HAY POR DIRECTOR
    8.- MOSTRAR LA PELICULA CON MAYOR RECAUDACIÓN, AGREGAR EL FORMATO A MONEDA Y LA PALBRA PESOS AL FINAL DE LA CANTIDAD
    9.- MOSTRAR LA PELICULA MAS ANTIGUA(MENOR ANIO DE ESTRENO) Y ANTEPONER LAS PALABRAS "ESTRENADA EN: " EL ANIO
    10.- DESGLOSAR EL DETALLE DE CADA PELICULA EN UNA SOLA COLUMNA (PIPES O CONCAT)
    EJEMPLO: LA PELICULA DE NOMBRE "" FUE DIRIGIDA POR "" EN EL ANIO "" TIENE UNA DURACIÓN DE "" MINUTOS ES DE GENERO "" Y TUVO UNA RECAUDACIÓN EN PESOS DE $"".00
*/


-- 1.-
SELECT ID_PELICULA, TITULO, DIRECTOR, GENERO, ANIO_ESTRENO, DURACION_MIN, TO_CHAR(RECAUDACION, 'fm$9,999,999,999.00') AS RECAUDACION_FORMAT FROM PELICULA
ORDER BY RECAUDACION DESC; 

-- 2.-
SELECT TO_CHAR(AVG(RECAUDACION), 'fm999999999.00') AS PROMEDIO_RECAUDACION FROM PELICULA 
WHERE ANIO_ESTRENO > 2002; 

-- 3.-
SELECT ID_PELICULA, LOWER(TITULO), DIRECTOR, GENERO, ANIO_ESTRENO, DURACION_MIN, RECAUDACION FROM PELICULA 
WHERE DURACION_MIN > 150; 

-- 4.-
SELECT ID_PELICULA, TITULO, DIRECTOR, GENERO, ANIO_ESTRENO, DURACION_MIN, RECAUDACION FROM PELICULA 
WHERE LOWER(GENERO) = 'ciencia ficción' 
ORDER BY ANIO_ESTRENO ASC;

-- 5.-
SELECT ID_PELICULA, TITULO, DIRECTOR, GENERO, ANIO_ESTRENO, DURACION_MIN, RECAUDACION FROM PELICULA 
WHERE RECAUDACION BETWEEN 500000000 AND 1500000000; 

-- 6.-
SELECT ID_PELICULA, TITULO, DIRECTOR, GENERO, ANIO_ESTRENO, DURACION_MIN, CONCAT(RECAUDACION, ' PESOS') AS RECAUDACION FROM PELICULA 
WHERE LOWER(GENERO) = 'comedia'; 

-- 7.-
SELECT UPPER(DIRECTOR) AS DIRECTOR, COUNT(ID_PELICULA) AS TOTAL_PELICULAS FROM PELICULA 
GROUP BY UPPER(DIRECTOR); 

-- 8.-
SELECT ID_PELICULA, TITULO, DIRECTOR, GENERO, ANIO_ESTRENO, DURACION_MIN, TO_CHAR(RECAUDACION, 'fm$9,999,999,999.00')||' PESOS' AS RECAUDACION FROM PELICULA 
WHERE RECAUDACION = (
    SELECT MAX(RECAUDACION) FROM PELICULA
); 

-- 9.-
SELECT ID_PELICULA, TITULO, DIRECTOR, GENERO, 'ESTRENADA EN: '||ANIO_ESTRENO AS ANIO_ESTRENO, DURACION_MIN, RECAUDACION FROM PELICULA 
WHERE ANIO_ESTRENO = (
    SELECT MIN(ANIO_ESTRENO) FROM PELICULA
); 

-- 10.-
SELECT
CONCAT(
    'LA PELICULA DE NOMBRE '||TITULO|| 
    ' FUE DIRIGIDA POR '||DIRECTOR||
    ' EN EL ANIO '||ANIO_ESTRENO||
    ' TIENE UNA DURACION DE '||DURACION_MIN||
    ' MINUTOS, ES DE GENERO '||GENERO||
    ' Y TUVO UNA RECAUDACION DE ', TO_CHAR(RECAUDACION, 'fm$9,999,999,999.00') 
) AS DETALLE_PELICULA FROM PELICULA; 