-- TRIGGER A NIVEL SENTENCIA (STATEMENT) --> SE EJECUTA UNA SOLA VEZ POR TIPO DE OPERACION DML
DELETE FROM CELULAR;
DELETE FROM BIT_CEL;


-- TRIGGER STATEMENT
CREATE OR REPLACE TRIGGER TR_I_U_D_CELULAR
AFTER INSERT OR UPDATE OR DELETE ON CELULAR
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(15);
BEGIN
    -- RECUPERAR EL ID VALIDO
    SELECT S_ID_CEL.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
    
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
    
    INSERT INTO BIT_CEL(ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES(LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
END;
/

SELECT * FROM CELULAR;
SELECT ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO FROM BIT_CEL;
INSERT INTO CELULAR VALUES(3, 'SAMSUNG', 'S F3', 'OCTA CORE', '123GB', 'ROJO', 300);
UPDATE CELULAR SET MARCA = 'IPHONE' WHERE ID_CELULAR = 1;
DELETE FROM CELULAR;

// REALIZAR EL TRIGGER A NIVEL SENTENCIA PARA MEDICAMENTO