-- ENTIDAD MEDICAMENTO
CREATE TABLE MEDICAMENTO(
    ID_MEDICAMENTO NUMBER,
    NOMBRE_GENERICO NVARCHAR2(100),
    NOMBRE_COMERCIAL NVARCHAR2(100),
    DESCRIPCION NVARCHAR2(255),
    LABORATORIO NVARCHAR2(100),
    PRECIO NUMBER,
    TIPO_SUMISTRO NVARCHAR2(100),
    CONSTRAINT MEDICAMENTO_PK PRIMARY KEY(ID_MEDICAMENTO)
);

-- ENTIDAD BITÁCORA
CREATE TABLE BIT_MED(
    ID_BIT_MEDI NUMBER,
    
    ID_MEDICAMENTO NUMBER,
    NOMBRE_GENERICO NVARCHAR2(100),
    NOMBRE_COMERCIAL NVARCHAR2(100),
    DESCRIPCION NVARCHAR2(255),
    LABORATORIO NVARCHAR2(100),
    PRECIO NUMBER,
    TIPO_SUMISTRO NVARCHAR2(100),
    
    NOMBRE_GENERICO_OLD NVARCHAR2(100),
    NOMBRE_COMERCIAL_OLD NVARCHAR2(100),
    DESCRIPCION_OLD NVARCHAR2(255),
    LABORATORIO_OLD NVARCHAR2(100),
    PRECIO_OLD NUMBER,
    TIPO_SUMISTRO_OLD NVARCHAR2(100),
    
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    
    CONSTRAINT BIT_MED_PK PRIMARY KEY(ID_BIT_MEDI)
);

-- SECUENCIA
-- DROP SEQUENCE S_ID_MED;
CREATE SEQUENCE S_ID_MED
START WITH 1
MINVALUE 1
MAXVALUE 999
NOCYCLE;
/

-- TRIGGER MÚLTIPLE
CREATE OR REPLACE TRIGGER TR_MULTIPLE_MED
AFTER INSERT OR UPDATE OR DELETE ON MEDICAMENTO
FOR EACH ROW
DECLARE
    LV_ID_BIT_MED NUMBER;
    LV_USER NVARCHAR2(100);
    LV_FECHA_MOV DATE;
BEGIN
    SELECT S_ID_MED.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT_MED, LV_USER, LV_FECHA_MOV FROM DUAL;
    
    IF INSERTING THEN
        INSERT INTO BIT_MED(ID_BIT_MEDI, ID_MEDICAMENTO, NOMBRE_GENERICO, NOMBRE_COMERCIAL, DESCRIPCION, LABORATORIO, PRECIO, TIPO_SUMISTRO,
            NOMBRE_GENERICO_OLD, NOMBRE_COMERCIAL_OLD, DESCRIPCION_OLD, LABORATORIO_OLD, PRECIO_OLD, TIPO_SUMISTRO_OLD,
            USUARIO, FECHA_MOV, MOVIMIENTO) 
        VALUES(LV_ID_BIT_MED, :NEW.ID_MEDICAMENTO, :NEW.NOMBRE_GENERICO, :NEW.NOMBRE_COMERCIAL, :NEW.DESCRIPCION, :NEW.LABORATORIO, :NEW.PRECIO, :NEW.TIPO_SUMISTRO,
            NULL, NULL, NULL, NULL, 0, NULL,
            LV_USER, LV_FECHA_MOV, 'INSERT');
    ELSIF UPDATING THEN
        INSERT INTO BIT_MED(ID_BIT_MEDI, ID_MEDICAMENTO, NOMBRE_GENERICO, NOMBRE_COMERCIAL, DESCRIPCION, LABORATORIO, PRECIO, TIPO_SUMISTRO,
            NOMBRE_GENERICO_OLD, NOMBRE_COMERCIAL_OLD, DESCRIPCION_OLD, LABORATORIO_OLD, PRECIO_OLD, TIPO_SUMISTRO_OLD,
            USUARIO, FECHA_MOV, MOVIMIENTO) 
        VALUES(LV_ID_BIT_MED, :OLD.ID_MEDICAMENTO, :NEW.NOMBRE_GENERICO, :NEW.NOMBRE_COMERCIAL, :NEW.DESCRIPCION, :NEW.LABORATORIO, :NEW.PRECIO, :NEW.TIPO_SUMISTRO,
            :OLD.NOMBRE_GENERICO, :OLD.NOMBRE_COMERCIAL, :OLD.DESCRIPCION, :OLD.LABORATORIO, :OLD.PRECIO, :OLD.TIPO_SUMISTRO,
            LV_USER, LV_FECHA_MOV, 'UPDATE');
    ELSIF DELETING THEN
        INSERT INTO BIT_MED(ID_BIT_MEDI, ID_MEDICAMENTO, NOMBRE_GENERICO, NOMBRE_COMERCIAL, DESCRIPCION, LABORATORIO, PRECIO, TIPO_SUMISTRO,
            NOMBRE_GENERICO_OLD, NOMBRE_COMERCIAL_OLD, DESCRIPCION_OLD, LABORATORIO_OLD, PRECIO_OLD, TIPO_SUMISTRO_OLD,
            USUARIO, FECHA_MOV, MOVIMIENTO) 
        VALUES(LV_ID_BIT_MED, :OLD.ID_MEDICAMENTO, NULL, NULL, NULL, NULL, 0, NULL,
            :OLD.NOMBRE_GENERICO, :OLD.NOMBRE_COMERCIAL, :OLD.DESCRIPCION, :OLD.LABORATORIO, :OLD.PRECIO, :OLD.TIPO_SUMISTRO,
            LV_USER, LV_FECHA_MOV, 'DELETE');
    END IF;
END;
/

-- TRIGGER A NIVEL SENTENCIA
CREATE OR REPLACE TRIGGER TR_I_U_D_MED
AFTER INSERT OR UPDATE OR DELETE ON MEDICAMENTO
DECLARE
    LV_ID_BIT_MED NUMBER;
    LV_USER NVARCHAR2(100);
    LV_FECHA_MOV DATE;
    LV_MOV NVARCHAR2(15);
BEGIN
    SELECT S_ID_MED.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT_MED, LV_USER, LV_FECHA_MOV FROM DUAL;
    
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
    
    INSERT INTO BIT_MED(ID_BIT_MEDI, USUARIO, FECHA_MOV, MOVIMIENTO) 
    VALUES(LV_ID_BIT_MED, LV_USER, LV_FECHA_MOV, LV_MOV);
END;
/

INSERT INTO MEDICAMENTO VALUES(1, 'TEMPRA', 'PARACETAMOL 500MG', 'ANALGESICO Y ANTIPIRETICO DE USO COMUN', 'LABORATORIOS GENERICOS', 250, 'TABLETAS');
INSERT INTO MEDICAMENTO VALUES(2, 'ADVIL', 'IBUPROFENO 400MG', 'ANTINFLAMATORIO PARA GOLPES', 'FARMACEUTICA DELTA', 320, 'CAPSULAS');
INSERT INTO MEDICAMENTO VALUES(3, 'AMOXIL', 'AMOXICILINA 500MG', 'ANTIBIOTICO PARA TRATAR INFECCIONES', 'BIOLAB', 375, 'CAPSULAS');
INSERT INTO MEDICAMENTO VALUES(4, 'CLARITIN', 'LORATADINA 10MG', 'ANTIHISTAMINICO QUE TRATA DIFERENTES ALERGIAS', 'SALUDPHARMA', 195, 'TABLETAS');
INSERT INTO MEDICAMENTO VALUES(5, 'LOSEC', 'OMEPRAZOL 2ML', 'INHIBIDOR PARA CONTRARESTAR LA GASTRITIS', 'GASTROMED', 110, 'INYECCION');

SELECT * FROM MEDICAMENTO;
-- SELECT * FROM BIT_MED;
SELECT ID_BIT_MEDI, USUARIO, FECHA_MOV, MOVIMIENTO FROM BIT_MED;


UPDATE MEDICAMENTO 
SET DESCRIPCION = 'NUEVA DESCRIPCION', PRECIO = 499.99
WHERE ID_MEDICAMENTO = 3;

UPDATE MEDICAMENTO 
SET TIPO_SUMISTRO = 'INYECCION', LABORATORIO = 'PFIZER'
WHERE ID_MEDICAMENTO = 1;

SELECT * FROM MEDICAMENTO;
-- SELECT * FROM BIT_MED;
SELECT ID_BIT_MEDI, USUARIO, FECHA_MOV, MOVIMIENTO FROM BIT_MED;


DELETE FROM MEDICAMENTO
WHERE ID_MEDICAMENTO IN(2, 4);

SELECT * FROM MEDICAMENTO;
-- SELECT * FROM BIT_MED;
SELECT ID_BIT_MEDI, USUARIO, FECHA_MOV, MOVIMIENTO FROM BIT_MED;

DELETE FROM MEDICAMENTO;
DELETE FROM BIT_MED;
