--  DDL: LENGUAJE DE DEFINICIÓN Y MODIFICACIÓN DE DATOS -> CREATE, ALTER, DROP, UPDATE
--  DM: LENGUAJE DE MANIPULACIÓN DE DATOS -> INSERT, SELECT, UPDATE Y DELETE
-- DCL: LENGUAJE DE CONTROL DE DATOS -> GRANT Y REVOKE

-- MODIFICAR LA SESIÓN ACTUAL PARA LA EJECUCIÓN DE SCRIPTS
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; -- CTRL + ENTER: PARA EJECUTAR LA LÍNEA

-- CREACIÓN DEL USUARIO Y CONTRASEÑA
CREATE USER CESARMARTINEZ IDENTIFIED BY CESARM;

-- OTROGAR PRIVILEGIOS AL USUARIO
GRANT ALL PRIVILEGES TO CESARMARTINEZ;
