-- DESACTIVAR LOS TRIGGER
ALTER TRIGGER TR_I_CELULAR DISABLE; 
ALTER TRIGGER TR_I_CELULAR ENABLE; 
ALTER TRIGGER TR_U_CELULAR DISABLE; 
ALTER TRIGGER TR_U_CELULAR ENABLE; 
ALTER TRIGGER TR_D_CELULAR DISABLE; 
ALTER TRIGGER TR_D_CELULAR ENABLE;

-- TRIGGER A NIVEL FILA, PARA UNA AUDITORIA, MÚLTIPLE
CREATE OR REPLACE TRIGGER TR_MULTIPLE_CEL
AFTER INSERT OR UPDATE OR DELETE ON CELULAR
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    -- RECUPERAR EL ID VALIDO(USANDO UN SEQUENCE)
    SELECT S_ID_CEL.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
    
    -- REGISTRO EN LA BITACORA
    IF INSERTING THEN
        INSERT INTO BIT_CEL(ID_BIT, ID_CELULAR, MARCA, MODELO, PROCESADOR, CAPACIDAD, COLOR, PRECIO,
            MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, CAPACIDAD_OLD, COLOR_OLD, PRECIO_OLD,
            USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES(LV_ID_BIT, :NEW.ID_CELULAR, :NEW.MARCA, :NEW.MODELO, :NEW.PROCESADOR, :NEW.CAPACIDAD, :NEW.COLOR, :NEW.PRECIO, 
            NULL, NULL, NULL, NULL, NULL, 0,
            LV_USUARIO, LV_FECHA, 'INSERT');
    ELSIF UPDATING THEN
        INSERT INTO BIT_CEL(ID_BIT, ID_CELULAR, MARCA, MODELO, PROCESADOR, CAPACIDAD, COLOR, PRECIO, 
            MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, CAPACIDAD_OLD, COLOR_OLD, PRECIO_OLD,
            USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES(LV_ID_BIT, :NEW.ID_CELULAR, :NEW.MARCA, :NEW.MODELO, :NEW.PROCESADOR, :NEW.CAPACIDAD, :NEW.COLOR, :NEW.PRECIO, 
            :OLD.MARCA, :OLD.MODELO, :OLD.PROCESADOR, :OLD.CAPACIDAD, :OLD.COLOR, :OLD.PRECIO,
            LV_USUARIO, LV_FECHA, 'UPDATE');
    ELSIF DELETING THEN
        INSERT INTO BIT_CEL(ID_BIT, ID_CELULAR, MARCA, MODELO, PROCESADOR, CAPACIDAD, COLOR, PRECIO, 
            MARCA_OLD, MODELO_OLD, PROCESADOR_OLD, CAPACIDAD_OLD, COLOR_OLD, PRECIO_OLD,
            USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES(LV_ID_BIT, :OLD.ID_CELULAR, NULL, NULL, NULL, NULL, NULL, 0, 
            :OLD.MARCA, :OLD.MODELO, :OLD.PROCESADOR, :OLD.CAPACIDAD, :OLD.COLOR, :OLD.PRECIO,
            LV_USUARIO, LV_FECHA, 'DELETE');
    END IF;
END;
/
DELETE FROM CELULAR;
DELETE FROM BIT_CEL;

INSERT INTO CELULAR VALUES(1, 'SAMSUNG', 'GALAXY 3', 'OCTA CORE', '128GB', 'NEGRO', 34000);
INSERT INTO CELULAR VALUES(2, 'HUAWEI', 'P40', 'OCTA CORE', '168GB', 'NEGRO', 20000);
UPDATE CELULAR SET MODELO = 'GALAXY POP' WHERE ID_CELULAR = 1;
DELETE FROM CELULAR WHERE ID_CELULAR = 1;

SELECT * FROM CELULAR;
SELECT * FROM BIT_CEL;
