-- PRACTICA PARA EL USO DE SENTENCIA CASE

-- CREAR LA TABLA PRODUCTO
CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER,
    NOMBRE NVARCHAR2(100),
    CATEGORIA NUMBER, -- 1.ALIMENTO, 2.BEBIDA, 3.ELECTRODOMESTICO, 4.ROPA, 5.LIMPIEZA
    PRECIO NUMBER,
    STOCK NUMBER,
    MARCA NVARCHAR2(100),
    CONSTRAINT PRODUCTO_PK PRIMARY KEY(ID_PRODUCTO)
);

DELETE FROM PRODUCTO;

INSERT INTO PRODUCTO VALUES(1,'ARROZ INTEGRAL 1KG',1,45.50,200,'LA MODERNA');
INSERT INTO PRODUCTO VALUES(2,'REFRESCO COLA 2L',2,28.00,150,'COCA-COLA');

INSERT INTO PRODUCTO VALUES(3,'CAMISA MANGA CORTA',4,19.99,75,'MODA JOVEN');
INSERT INTO PRODUCTO VALUES(4,'LICUADORA 3 VELOCIDADES',3,125,50,'ELECTROLUZ');


INSERT INTO PRODUCTO VALUES(5,'CEREAL ZUCARITAS 500G',1,65,40,'KELLOGGS');
INSERT INTO PRODUCTO VALUES(6,'REFRESCO COCA-COLA 2L',2,38,60,'COCA-COLA');

INSERT INTO PRODUCTO VALUES(7,'PLAYERA DEPORTIVA',4,299.00,50,'NIKE');
INSERT INTO PRODUCTO VALUES(8,'PANTALÓN CASUAL',4,499.00,40,'LEVI’S');

-- ACTIVIDADES

-- CONSULTA CASE PARA MOSTRAR LA CATEGORIA
SELECT ID_PRODUCTO, NOMBRE,
(CASE CATEGORIA
    WHEN 1 THEN 'ALIMENTO'
    WHEN 2 THEN 'BEBIDA'
    WHEN 3 THEN 'ELECTRODOMESTICO'
    WHEN 4 THEN 'ROPA'
    WHEN 5 THEN 'LIMPIEZA'
    ELSE 'SIN CATEGORIA'
    END
) AS CATEGORIA, PRECIO, STOCK, MARCA FROM PRODUCTO;

-- CONSULTA CASE PARA CALIFICAR EL PRECIO(BARATO, MEDIO, CARO)
SELECT ID_PRODUCTO, NOMBRE, CATEGORIA,
(CASE
    WHEN PRECIO BETWEEN 0 AND 99.99 THEN 'BARATO, TIENE UN COSTO DE: ' || TO_CHAR(PRECIO, 'fm$999.00')
    WHEN PRECIO BETWEEN 100 AND 299.99 THEN 'MEDIO, TIENE UN COSTO DE: ' || TO_CHAR(PRECIO, 'fm$999.00')
    WHEN PRECIO >= 300 THEN 'CARO, TIENE UN COSTO DE: ' || TO_CHAR(PRECIO, 'fm$999.00')
    ELSE 'PRECIO NO DEFINIDO'
    END
) AS PRECIO, STOCK, MARCA FROM PRODUCTO;

-- CONSULTA CASE PARA CALIFICAR EL STOCK (SOBRANTE, SUFICIENTE, ESCASO)
SELECT ID_PRODUCTO, NOMBRE, CATEGORIA, PRECIO,
(CASE
    WHEN STOCK BETWEEN 0 AND 59 THEN 'ESCASO, HAY UN STOCK DE: ' || STOCK || ' UNIDADES'
    WHEN STOCK BETWEEN 60 AND 149 THEN 'SUFICIENTE, HAY UN STOCK DE: ' || STOCK || ' UNIDADES'
    WHEN STOCK >= 150 THEN 'SOBRANTE, HAY UN STOCK DE: ' || STOCK || ' UNIDADES'
    ELSE 'STOCK NO DEFINIDO'
    END
) AS STOCK, MARCA FROM PRODUCTO;

