-- CREAR UNA ENTIDAD CON DDL
CREATE TABLE EMPLEADO(
    ID_CLIENTE NUMBER, -- ALMACENA DATOS DE TIPO NÚMERICO
    NOMBRE NVARCHAR2(100), -- ES ÚNICO DE ORACLE Y SIRVE PARA ALMACENAR DATOS DE LONGITUD
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
);

-- DML
-- INSERTAR VALORES EN LA TABLA
INSERT INTO EMPLEADO VALUES(1, 'Roberto', 'Morales', 35, 'PROGRAMADOR JAVA', 'TI');
COMMIT; -- UNA VEZ QUE SE EJECUTA UNA SENTENCIA DML, DEBEMOS CONFIRMAR LOS CAMBIOS PARA TERMINAR CON LA TRANSACCIÓN REALIZADA
-- SI UNA TRANSACCIÓN SE QUEDA SIN CONFIRMAR LA BD QUEDARA BLOQUEADA POR EL USUARIO QUE REALIZÓ LA TRANSACCIÓN Y NINGÚN OTRO USUARIO PODRA REALIZAR
-- OPERACIONES DE PERSISTENCIA EN LA BD

SELECT * FROM EMPLEADO;

-- OPERACIONES PARA ELIMINAR
-- EJECUTAR UN DML PARA ELIMINAR LOS REGISTROS DE LA TABLA
DELETE FROM EMPLEADO; -- ELIMINA EL CONTENIDO EN LA TABLA(UNICAMENTE LOS REGISTROS)
-- EJECUTAR UN DDL PARA ELIMINAR LA TABLA
DROP TABLE EMPLEADO; -- ELIMINA TODA LA TABLA(DEJA DE EXISTIR EN LA BD)

-- USO DE LOS CONSTRAINT(3 FORMAS DIFERENTES)
-- CREAR UNA ENTIDAD CON PRIMARY KEY --> PRIMERA FORMA
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
);

--DDL CON PRIMARY KEY --> SEGUNDA FORMA
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    PRIMARY KEY(ID_EMPLEADO)
);

--DDL CON PRIMARY KEY --> TERCERA FORMA
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY(ID_EMPLEADO)
);
