-- AGREGAR INSERCIONES EN LA TABLA EMPLEADO
SELECT * FROM EMPLEADO;

INSERT INTO EMPLEADO VALUES(1, 'MAURICIO', 'SANCHEZ', 25, 'AUX. ADMINISTRATIVO', 'RR.HH');
INSERT INTO EMPLEADO VALUES(2,'EDUARDO','BLANCO',25,'PROGRAMADOR JR','SISTEMAS');
INSERT INTO EMPLEADO VALUES(3, 'CHENTE', 'VAZQUEZ', 42, 'INTENDENTE', 'LIMPIEZA');
INSERT INTO EMPLEADO VALUES(4, 'JOSE', 'GARCIA', 25, 'PROGRAMADOR .NET', 'TI');
INSERT INTO EMPLEADO VALUES(5,'SERGIO','COVARRUBIAS',25,'MANTENIMIENTO','SIS');

-- MODIFICAR O CAMBIAR EL NOMBRE DE LA COLUMNA
ALTER TABLE EMPLEADO RENAME COLUMN APP TO APELLIDO;

-- DML PARA ACTUALIZAR 
UPDATE EMPLEADO SET DEPARTAMENTO = 'SISTEMAS' WHERE ID_EMPLEADO = 4;

--FUNCIÓN ORDER BY
SELECT * FROM EMPLEADO ORDER BY EDAD ASC;
SELECT * FROM EMPLEADO ORDER BY EDAD DESC;

-- BUSQUEDA DE INFORMACIÓN CON CARACTERES EN ESPECÍFICO
-- BUSCAR EMPLEADO QUE EMPIECE CON LA LETRA 'E'
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'E%';
-- BUSCAR EMPLEADO QUE SU NOMBRE CONTENGA LA LETRA 'I'
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%I%';
-- BUSCAR EMPLEADO QUE TERMINE CON LA LETRA 'O'
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%O';

-- USO DE LA TABLA DUAL: ES UNA TABLA ESPECIAL DE UNA SOLA FILA Y UNA SOLA COLUMNA LLAMADA "DUMMY"
-- ESTÁ SE CREA AUTOMATICAMENTE Y ESTA DISPONIBLE PARA TODOS LOS USUARIOS, SE UTILIZA PARA EVALUAR
-- EXPRESIONES, LLAMAR FUNCIONES Y OBTENER EL VALOR DE PSEUDOCOLUMNAS COMO SYSDATE O USER.
-- PROPORCIONA UN LUGAR PARA EJECUTAR SENTENCIAS SELECT QUE NO REQUIEREN DATOS DE UNA TABLA REAL
SELECT 5 + 5 AS SUMA FROM DUAL;

-- USO DE LA FUNCIÓN LENGHT
SELECT LENGTH('ESTA ES UNA CADENA DE PRUEBA PARA EL USO DE LENGHT') AS TAMNIO FROM DUAL;

-- BUSCAR CON MÁS CONDICIONES
-- BUSCAR EMPLEADOS MAYORES DE 25
SELECT * FROM EMPLEADO WHERE EDAD > 25;
-- BUSCAR EMPLEADO MENORES DE 30
SELECT * FROM EMPLEADO WHERE EDAD < 30;
-- BUSCAR EMPLEADOS MAYORES DE 24 Y MENORES DE 28
SELECT * FROM EMPLEADO WHERE EDAD > 24 AND EDAD < 28;
-- RANGO BETWEEN
SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 24 AND 28;
-- BUSCAR LOS EMPLEADOS CON EL ID 1, 3, 5
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO = 1 OR ID_EMPLEADO = 3 OR ID_EMPLEADO = 5;
-- USO DE LA FUNCIÓN IN
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1, 3, 5);

-- FUNCIÓN GROPU BY
SELECT DEPARTAMENTO FROM EMPLEADO GROUP BY DEPARTAMENTO;
-- FUNCIÓN COUNT
SELECT DEPARTAMENTO, COUNT(ID_EMPLEADO) AS NUMERO_EMPLEADOS FROM EMPLEADO WHERE DEPARTAMENTO IS NOT NULL GROUP BY DEPARTAMENTO;

-- CONTAR LOS EMPLEADOS QUE TENGAN MÁS DE 25
SELECT COUNT(ID_EMPLEADO) AS TOTAL_EMPLEADO FROM EMPLEADO WHERE EDAD > 25;

-- FUNCIÓN DE AGREGACIÓN SUM
SELECT SUM(EDAD) AS SUMA_EDADES FROM EMPLEADO WHERE APELLIDO LIKE '%A%';

-- FUNCIÓN DE AGREGACIÓN MAX
SELECT MAX(EDAD) AS EDAD_MAX FROM EMPLEADO;
-- FUNCIÓN DE AGREGACIÓN MIN
SELECT MIN(EDAD) AS EDAD_MAX FROM EMPLEADO;

-- FUNCIÓN AVG(AVERAGE) - PROMEDIO
SELECT AVG(EDAD) AS EDAD_PROMEDIO FROM EMPLEADO;
-- FUNCIÓN ROUND
SELECT ROUND(AVG(EDAD), 2) AS EDAD_PROMEDIO FROM EMPLEADO;
-- USO DE TO_CHAR CON FORMATO
-- PUEDE CAMBIAR EL FORMATO NUMÉRICO(EJEMPLO, AGREGAR VALORES $1,984,243.99)
SELECT TO_CHAR(AVG(EDAD), 'fm99.0') AS PROMEDIO_EDAD FROM EMPLEADO WHERE EDAD < 32;
-- DARLE UN FORMATO DIFERENTE
-- FUNCIÓN CONCAT: EN UN ASOLA COLUMNA, DESGLOSA LA INFORMACIÓN Y CONCATENA TEXTO EXTRA
SELECT CONCAT(CONCAT('EL EMPLEADO', ' '), NOMBRE) AS DETALLE FROM EMPLEADO;

-- USO DE 'PIPE' O BARRA LATERAL --> ||
SELECT 'EL EMPLEADO '||NOMBRE||' '||APELLIDO||' CON LA EDAD DE '||EDAD||' AÑOS, TRABAJA EN EL DEPARTAMENTO DE '||DEPARTAMENTO||' COMO PUESTO DE '||PUESTO AS DETALLE_EMPLEADO FROM EMPLEADO;

-- SUBCONSULTA O UNA CONSULTA ANIDADA
SELECT * FROM EMPLEADO WHERE EDAD = (
    SELECT MAX(EDAD)
    FROM EMPLEADO
    WHERE DEPARTAMENTO = 'SIS'
);

---
SELECT * FROM EMPLEADO WHERE EDAD = (
    SELECT MIN(EDAD)
    FROM EMPLEADO
    WHERE DEPARTAMENTO = 'SIS'
);