-- COMO RECUPERAR LA FECHA DE SISTEMA
SELECT SYSDATE FROM DUAL;
-- MODIFICAR EL FROMATO DE LA FECHA
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

-- COMO RECUPERAR LA FECHA DE SISTEMA
SELECT SYSDATE FROM DUAL;

-- RECUPERAR EL USUARIO
SELECT USER FROM DUAL;

-- OBTENER UN ID VALIDO PARA MI TABLA BITACORA
SELECT NVL(MAX(ID_BIT), 0) + 1 AS ID_BITACORA FROM BIT_CEL;

COMMIT;