/* SECUENCIA O SEQUENCE: SE EMPLEA PARA GENERAR CALORES ENTEROS SECUENCIALES UNICOS Y ASIGNARSELOS A CAMPOS NÚMERICOS
GENERALMENTE SE USASN PARA LAS LLAVES PRIMARIAS ASEGURANDO QUE NO HAYA ID'S REPETIDOS
*/

CREATE SEQUENCE S_ID_CEL
START WITH 1
MAXVALUE 999
MINVALUE 1
NOCYCLE;
/

SELECT S_ID_CEL.NEXTVAL FROM DUAL;