/* CASE
WHEN CONDICION_1 THEN RESULTADO_1
WHEN CONDICION_2 THEN RESULTADO_2
....
ELSE RESULTADO_PREDETERMINADO
END
*/

-- CREAR CON DDL DE LA ENTIDAD LIBRO
CREATE TABLE LIBRO(
    ID_LIBRO NUMBER,
    NOMBRE NVARCHAR2(100),
    AUTOR NVARCHAR2(100),
    GENERO NUMBER, -- 1.DRAMA, 2.TERROR, 3.CIENCIA FICCION, 4.NOVELA, 5.THRILLER
    NO_PAGINAS NUMBER,
    PRECIO NUMBER,
    EDITORIAL NVARCHAR2(100),
    CONSTRAINT LIBRO_PK PRIMARY KEY(ID_LIBRO)
);

INSERT INTO LIBRO VALUES(1, 'LOS JUEGOS DEL HAMBRE', 'SUZZANE COLLINS', 4, 500, 345, 'MOLINO');
INSERT INTO LIBRO VALUES(2, 'HARRY POTTER Y EL PRINCIPE MESTIZO', 'J..K ROWLIN', 0, 700, 0, 'SALAMNDRA');
INSERT INTO LIBRO VALUES(3,'MAZE RUNNER: CORRER O MORIR','JAMES DASHNER',1,400,299,'VYR EDITORAS');
INSERT INTO LIBRO VALUES(4,'DIVERGENTE','VERONICA ROTH',1,487,320,'HARPER COLLINS');
INSERT INTO LIBRO VALUES(5,'IT','STEPHEN KING',2,1138,350,'VIKING PRESS');
INSERT INTO LIBRO VALUES(6,'LA CHICA DEL TREN','PAULA HAWKINS',5,395,199.99,'RIVERHEAD BOOKS');
INSERT INTO LIBRO VALUES(7, 'EL NOMBRE DE LA ROSA', 'UMBERTO ECO', 5, 512, 380, 'BOMPIANI');
INSERT INTO LIBRO VALUES(8, 'LA CASA DE LOS ESPÍRITUS', 'ISABEL ALLENDE', 1, 490, 330, 'DEBOLSILLO');
INSERT INTO LIBRO VALUES(9, 'EL PSICOANALISTA', 'JOHN KATZENBACH', 5, 600, 279.75, 'EDICIONES B');
INSERT INTO LIBRO VALUES(10, 'CIEN AÑOS DE SOLEDAD', 'GABRIEL GARCÍA MÁRQUEZ', 1, 200,259.90, 'SUDAMERICANA');
COMMIT;

SELECT * FROM LIBRO;
DELETE FROM LIBRO;

-- USO DE CASE USANDOLO COMO COMPLEMENTO
SELECT ID_LIBRO, NOMBRE, AUTOR, (
    CASE GENERO 
    WHEN 1 THEN 'DRAMA'
    WHEN 2 THEN 'TERROR'
    WHEN 3 THEN 'CIENCIA FICCION'
    WHEN 4 THEN 'NOVELA'
    WHEN 5 THEN 'THRILLER'
    ELSE 'SIN GENERO'
    END
) AS GENERO,
NO_PAGINAS,
PRECIO,
EDITORIAL
FROM LIBRO;


-----
SELECT ID_LIBRO, NOMBRE, AUTOR, GENERO,
(CASE
    WHEN NO_PAGINAS > 500 THEN 'ES LARGO TIENE: ' || NO_PAGINAS || ' PAGINAS'
    WHEN NO_PAGINAS <= 500 THEN 'ES CORTO TIENE: ' || NO_PAGINAS || ' PAGINAS'
    ELSE 'NO. PAGINAS DESCONOCIDO'
    END
) AS NO_PAGINAS, PRECIO, EDITORIAL FROM LIBRO;